---
title: "MI_map"
author: "Yvonne Lian"
date: '2022-07-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  echo = TRUE
)
library(tidyverse)
library(leaflet)
library(tidycensus)
library(viridis)
library(sf)
library(dplyr)
library(knitr)
library(shinythemes)
library(shiny)
library(htmltools)
library(htmlwidgets)
library(rsconnect)
library(rgeos)
```


```{r setup, include=FALSE}
#Import MI 2022 county shape file
MI_county_2022 <- st_read("data/MI_data/MI_Counties/Counties_(v17a).shp") %>%
  st_as_sf(coords = c("longitude", "latitude", crs = 4326)) %>%
  st_transform(4326)

#Import MI 2022 SD shape file
MI_SD_2022 <- st_read("data/MI_data/MI_School_Districts/School_Districts_(v17a).shp") %>%
  st_as_sf(coords = c("longitude", "latitude", crs = 4326)) %>%
  st_transform(4326)

# Import MI 2022 Senate district shape file
MI_senate_2022 <- st_read("data/MI_data/MI_Senate_Districts/Linden.shp") %>%
  st_as_sf(coords = c("longitude", "latitude", crs = 4326)) %>%
  st_transform (4326)

#Import MI 2022 House district shape file
MI_house_2022 <- st_read("data/MI_data/MI_House_Districts/Hickory.shp") %>%
  st_as_sf(coords = c("longitude", "latitude", crs = 4326)) %>%
  st_transform(4326)

#Import MI 2022 Townships shape file
MI_townships_2022 <- st_read("data/MI_data/Civil_Divisions_Townships/Minor_Civil_Divisions_(Cities_%26_Townships)_.shp") %>%
  st_as_sf(coords = c("longitude", "latitude", crs = 4326)) %>%
  st_transform(4326)


```



```{r}
#Clean data + static labels

#MI 2022 Senate district
MI_senate_2022 <- MI_senate_2022 %>%
  arrange(as.numeric(DISTRICT))

MI_senate_2022_centroid <- as.data.frame(gCentroid(as(MI_senate_2022, "Spatial"), byid = TRUE, id = MI_senate_2022$DISTRICT))

MI_senate_2022_centroid$ID <- 1:nrow(MI_senate_2022_centroid)


#MI 2022 House district

MI_house_2022 <- MI_house_2022 %>%
  arrange(as.numeric(DISTRICT))

MI_house_2022_centroid <- as.data.frame(gCentroid(as(MI_house_2022, "Spatial"), byid = TRUE, id = MI_house_2022$DISTRICT))

MI_house_2022_centroid$ID <- 1:nrow(MI_house_2022_centroid)

```




```{r}
MI_map <- leaflet(options = leafletOptions(zoomControl = TRUE,
                                 zoomSnap = 0.25,
                                 zoomDelta = 0.25)) %>%
	addTiles(group = "OSM") %>%
	setView(lat = 44, lng = -85, zoom = 7) %>%
	addProviderTiles("CartoDB.Positron", group = "CartoDB.Positron" ) %>%
  addPolygons(data = MI_townships_2022,
				fillColor = "transparent",
				stroke = TRUE,
				color = "lightsteelblue",
				weight = 0.6,
				opacity = 0.5,
				highlight = highlightOptions(
				  stroke = TRUE,
				  weight = 2, 
				  opacity = 0.7,
				  fill = "lavender",
				  color = "lightsteelblue",
				  fillColor = "lavender", 
				  fillOpacity = 0.3,
				  bringToFront = FALSE),
				label = paste0(htmlEscape(MI_townships_2022$LABEL)),
				group = "Townships 2022") %>%
   addPolygons(data = MI_county_2022,
				fillColor = "cornflowerblue",
				stroke = TRUE,
				color = "cornflowerblue",
				weight = 1.3,
				opacity = 0.8,
				fillOpacity = 0.3,
				highlight = highlightOptions(
				  stroke = TRUE,
				  weight = 2, 
				  opacity = 0.7,
				  fill = "lightcyan",
				  color = "cornflowerblue",
				  fillColor = "lightcyan", 
				  fillOpacity = 0.7,
				  bringToFront = FALSE),
				label = paste0("County: ",
				htmlEscape(MI_county_2022$DISTRICT)),
				group = "County 2022") %>%
   addPolygons(data = MI_SD_2022,
				fillColor = "darkcyan",
				stroke = TRUE,
				color = "darkcyan",
				weight = 1.3,
				opacity = 0.8,
				fillOpacity = 0.3,
				highlight = highlightOptions(
				  stroke = TRUE,
				  weight = 2, 
				  opacity = 0.7,
				  fill = "lightcyan",
				  color = "darkcyan",
				  fillColor = "lightcyan", 
				  fillOpacity = 0.7,
				  bringToFront = FALSE),
				label = paste0("2022 SD ",
			htmlEscape(MI_SD_2022$NAME)),
				group = "SD district 2022") %>%
		addPolygons(data = MI_senate_2022,
				fillColor = "darkturquoise",
				stroke = TRUE,
				color = "darkturquoise",
				weight = 1.2,
				opacity = 0.8,
				fillOpacity = 0.2,
				highlight = highlightOptions(
				  stroke = TRUE,
				  weight = 2, 
				  opacity = 0.7,
				  fill = "lightcyan",
				  color = "darkturquoise",
				  fillColor = "lightcyan", 
				  fillOpacity = 0.7,
				  bringToFront = FALSE),                
				label= paste0("2022 Senate District ", htmlEscape(MI_senate_2022$DISTRICT)),
				group = "Senate District 2022") %>%
  		addPolygons(data = MI_house_2022,
				fillColor = "darkseagreen",
				stroke = TRUE,
				color = "forestgreen",
				weight = 1,
				opacity = 0.4,
				fillOpacity = 0.2,
				highlight = highlightOptions(
				  stroke = TRUE,
				  weight = 2, 
				  opacity = 0.7,
				  fill = "honeydew",
				  color = "forestgreen",
				  fillColor = "honeydew", 
				  fillOpacity = 0.7,
				  bringToFront = FALSE),                
				label= paste0("2022 House District ", htmlEscape(MI_house_2022$DISTRICT)),
				group = "House District 2022") %>%
  addPolygons(data = MI_senate_2022,
				fillColor = "transparent",
				stroke = TRUE,
				color = "gold",
				weight = 3,
				opacity = 0.6,
				fillOpacity = 0.2,
				highlight = highlightOptions(
				  stroke = TRUE,
				  weight = 2, 
				  opacity = 0.7,
				  fill = "cornsilk",
				  color = "gold",
				  fillColor = "cornsilk", 
				  fillOpacity = 0.2,
				  bringToFront = FALSE),                
				label= paste0("2022 Senate District ", htmlEscape(MI_senate_2022$DISTRICT)),
				group = "Senate District lines 2022") %>%
  addPolygons(data = MI_house_2022,
				fillColor = "transparent",
				stroke = TRUE,
				color = "darkorange",
				weight = 3,
				opacity = 0.6,
				highlight = highlightOptions(
				  stroke = TRUE,
				  weight = 2, 
				  opacity = 0.7,
				  fill = "papayawhip",
				  color = "darkorange",
				  fillColor = "papayawhip", 
				  fillOpacity = 0.2,
				  bringToFront = FALSE),                
				label= paste0("2022 House District ", htmlEscape(MI_house_2022$DISTRICT)),
				group = "House District lines 2022") %>%
  addLabelOnlyMarkers(data = MI_senate_2022_centroid, ~x, ~y, label = ~as.character(ID),
						labelOptions = labelOptions(noHide = TRUE,
													direction = "center",
													offset = c(0, 0), opacity = 1, 
													textsize = "15px", textOnly = TRUE, 
													style = list("font-style" = "bold")),
							group = "Senate District 2022") %>%
   addLabelOnlyMarkers(data = MI_senate_2022_centroid, ~x, ~y, label = ~as.character(ID),
						labelOptions = labelOptions(noHide = TRUE,
													direction = "center",
													offset = c(0, 0), opacity = 0.7, 
													textsize = "20px", textOnly = TRUE, 
													style = list("font-style" = "bold")),
							group = "Senate District lines 2022") %>%
   addLabelOnlyMarkers(data = MI_house_2022_centroid, ~x, ~y, label = ~as.character(ID),
						labelOptions = labelOptions(noHide = TRUE,
													direction = "center",
													offset = c(0, 0), opacity = 1, 
													textsize = "15px", textOnly = TRUE, 
													style = list("font-style" = "bold")),
							group = "House District 2022") %>%
   addLabelOnlyMarkers(data = MI_house_2022_centroid, ~x, ~y, label = ~as.character(ID),
						labelOptions = labelOptions(noHide = TRUE,
													direction = "center",
													offset = c(0, 0), opacity = 0.7, 
													textsize = "20px", textOnly = TRUE, 
													style = list("font-style" = "bold")),
							group = "House District lines 2022") %>%
  	 	 addLegend("bottomright", 
			colors = c("darkturquoise","darkseagreen", "darkcyan", "cornflowerblue", "","lightsteelblue", "gold", "darkorange"), 
			labels = c("Senate district 2022","House district 2022", "SD district 2022", "County 2022", "",  "Townships 2022","Senate District lines 2022", "House district lines 2022" ),
			title = "MI districts",
			opacity = 1) %>%    
hideGroup(c( "Senate District 2022",
						"House District 2022",
            "SD district 2022",
            "County 2022",
						"Townships 2022",
						"Senate District lines 2022",
            "House District lines 2022")) %>%
	showGroup(c("Townships 2022", "Senate District 2022")) %>%
	addLayersControl(overlayGroups= c(
									  "Senate District 2022",
									  "House District 2022",
									  "SD district 2022",
									  "County 2022",
									  "Townships 2022",
									  "Senate District lines 2022",
									  "House District lines 2022"), 
					 baseGroups = c("CartoDB.Positron")) 


MI_map
```

